package com.resourcifyproject.resourcify;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.rest.webmvc.ResourceNotFoundException;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.*;

@Controller
@CrossOrigin
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private ResourceRepository resourcerepository;
    @Autowired
    private ItemRepository itemRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/add")
    public @ResponseBody String addNewUser (@RequestBody JsonNode payload)
    {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if (userRepository.findByUsername(payload.get("username").textValue()).isPresent()) {
            return "User already Exists";
        }
        User n = new User();
        n.setRole(payload.get("role").textValue());
        n.setUsername(payload.get("username").textValue());
        n.setPassword(payload.get("password").textValue());
        n.setPassword(passwordEncoder.encode(n.getPassword()));
        n.setLastname(payload.get("lastname").textValue());
        n.setFirstname(payload.get("firstname").textValue());
        userRepository.save(n);
        return "Saved";
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/add/funds")
    public @ResponseBody String addFunds (@RequestBody JsonNode payload) throws UsernameNotFoundException {
        User user = userRepository.findByUsername(payload.get("username").textValue()).get();
        user.setAvailableFunds( user.getAvailableFunds() + payload.get("funds").floatValue() );

        return "Added Funds";
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/add/resource")
    public @ResponseBody String addNewResource (@RequestBody JsonNode payload) {
        Resource r = new Resource();
        r.setResourceCategory(payload.get("resource_category").textValue());
        r.setName(payload.get("name").textValue());
        r.setDescription(payload.get("description").textValue());
        r.setImage(payload.get("image").textValue());
        r.setModelNumber(payload.get("model_number").textValue());
        r.setBorrowPrice(Float.parseFloat(payload.get("borrow_price").textValue()));
        r.setSalePrice(Float.parseFloat(payload.get("sale_price").textValue()));
        resourcerepository.save(r);
        return "Added Resource";
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/add/item")
    public @ResponseBody String addNewItem (@RequestBody JsonNode payload) {
        Resource r = resourcerepository.findById(payload.get("resource_id").asInt()).get();
        Item i = new Item();
        i.setResource(r);
        i.setItemType(payload.get("item_type").textValue());
        i.setSerialNumber(payload.get("serial_number").textValue());
        i.setAvailable(true);
        itemRepository.save(i);
        return "Added Item";
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/get/resource")
    public @ResponseBody List<Resource> getResources(@RequestBody JsonNode payload) {
        return resourcerepository.findByResourceCategory(payload.get("resource_category").asText()).get();
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/get/sale")
    public @ResponseBody int getAvailPurchase(@RequestBody JsonNode payload) {
        return itemRepository.countItems(payload.get("resource_id").asInt(),0, true);
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/get/borrow")
    public @ResponseBody int getAvailBorrow(@RequestBody JsonNode payload) {
        return itemRepository.countItems(payload.get("resource_id").asInt(), 1, true);
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/get/user/purchased")
    public @ResponseBody List<Item> getPurchasedItems(HttpServletRequest request) throws ResourceNotFoundException {
        User user = userRepository.findByUsername(request.getRemoteUser()).get();
        List<Item> purchasedItems = itemRepository.getItemsByUsername(user.getUsername(), 0);
        if(purchasedItems.isEmpty()){
            throw new ResourceNotFoundException("You have not purchased any items!");
        }
        return purchasedItems;
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/get/user/borrowed")
    public @ResponseBody List<Item> getBorrowedItems(HttpServletRequest request) throws ResourceNotFoundException {
        User user = userRepository.findByUsername(request.getRemoteUser()).get();
        List<Item> borrowedItems = itemRepository.getItemsByUsername(user.getUsername(), 1);
        if(borrowedItems.isEmpty()){
            throw new ResourceNotFoundException("You are not currently borrowing any items!");
        }
        return borrowedItems;
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/get/user/")
    public @ResponseBody User getUser(HttpServletRequest request) {
        User user = userRepository.findByUsername(request.getRemoteUser()).get();
        return user;
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/do/cart/")
    public @ResponseBody String setCart(HttpServletRequest request, @RequestBody JsonNode payload) {
        User user = userRepository.findByUsername(request.getRemoteUser()).get();
        List<String> cart = new ArrayList<String>();
        for (JsonNode item : payload) {
            cart.add(item.asText());
        }
        user.setCart(cart);
        return "Cart Updated!";
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/do/purchase")
    public @ResponseBody String doPurchase(HttpServletRequest request, @RequestBody JsonNode payload) {
        User user = userRepository.findByUsername(request.getRemoteUser()).get();
        Resource resource = resourcerepository.findById(payload.get("resource_id").asInt()).get();
        if ( user.getAvailableFunds() < resource.getSalePrice() ) {
            throw new ForbiddenException(); //They don't have enough money
        }
        if ( itemRepository.countItems(payload.get("resource_id").asInt(),0, true) < 1 ) {
            throw new ArithmeticException(); //There is not an item available to purchase
        }
        Item itemToPurchase = itemRepository.getItemForTransaction(payload.get("resource_id").asInt(),0, true);
        itemToPurchase.setAvailable(false);
        itemToPurchase.setUsername(user.getUsername());
        itemToPurchase.setTransactionPrice(resource.getSalePrice());
        itemToPurchase.setTransactionTime(LocalDateTime.now());
        return "Purchase Successful!";
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/do/borrow")
    public @ResponseBody String doBorrow(HttpServletRequest request, @RequestBody JsonNode payload) {
        User user = userRepository.findByUsername(request.getRemoteUser()).get();
        Resource resource = resourcerepository.findById(payload.get("resource_id").asInt()).get();
        if ( user.getAvailableFunds() < resource.getBorrowPrice() ) {
            throw new ForbiddenException(); //They don't have enough money
        }
        if ( itemRepository.countItems(payload.get("resource_id").asInt(),1, true) < 1 ) {
            throw new ArithmeticException(); //There is not an item available to borrow
        }
        Item itemToBorrow = itemRepository.getItemForTransaction(payload.get("resource_id").asInt(),0, true);
        itemToBorrow.setAvailable(false);
        itemToBorrow.setUsername(user.getUsername());
        itemToBorrow.setTransactionPrice(resource.getBorrowPrice());
        itemToBorrow.setTransactionTime(LocalDateTime.now());
        itemToBorrow.setBorrowTime(payload.get("borrow_time").asLong());
        return "Borrow Successful!";
    }

    @CrossOrigin(origins = "http://localhost:3000")
    @PostMapping(path="/do/return")
    public @ResponseBody String doReturn(@RequestBody JsonNode payload) {
        Item item = itemRepository.findById(payload.get("item_id").asInt()).get();
        item.setTransactionTime(null);
        item.setTransactionPrice(null);
        item.setBorrowTime(null);
        return "Return Successful!";
    }

    @ResponseStatus(HttpStatus.FORBIDDEN)
    public class ForbiddenException extends RuntimeException {}

    @GetMapping(path="/confirm")
    public @ResponseBody String isAdmin (HttpServletRequest request) {
        User user = userRepository.findByUsername(request.getRemoteUser()).get();
        if(user != null) {
            if ((user.getRole()) == Role.valueOf("ADMIN")) {
                return "Success";
            }
        }
        throw new ForbiddenException();
    }
}